### ISSUE TITLE
在react下使用sablejs 卡顿

### ISSUE THREAD

**Issue by Ctrl30** [ErosZy/sablejs#35]
在react环境下使用sablejs 会导致整个页面崩溃
[codesandbox](https://codesandbox.io/s/magical-firefly-vjiikd?file=/src/App.js)

**Comment by ErosZy** [comment]
we don't know what your original code, but we see you call fib function. the fib function is very expensive, please change n  to be less 30 and try again.

**Comment by Ctrl30** [comment]
在这个示例里我没有使用斐波那契函数，只是简单的打印，但是在打印后就卡住了

**Comment by ErosZy** [comment]
@Ctrl30 can you provide demo code?

**Comment by Ctrl30** [comment]
@ErosZy https://codesandbox.io/s/magical-firefly-vjiikd?file=/src/App.js
先点击clime me按钮 然后再点sablejs按钮，然后再点击click me按钮 发现没有console打出，整个进程卡住了
<img width="876" alt="image" src="https://user-images.githubusercontent.com/26598048/191881458-21683fc6-d381-40aa-ab2c-313d3fd72ad2.png">

**Comment by ErosZy** [comment]
@Ctrl30 i mean the original code which compiled by sablejs.

**Comment by Ctrl30** [comment]
@ErosZy  不好意思，是我使用了斐波那契 函数导致的卡顿，在加密的过程的代码中不能使用太复杂的计算吗

**Comment by ErosZy** [comment]
@Ctrl30 sablejs has no jit, so the fib function is very expensive, but you can use simple crypto(like aes/des and so on...), that's just ok.
