### ISSUE TITLE
HI, could you help me to solve this problem,thx!

### ISSUE THREAD

**Issue by luziang0603** [ErosZy/sablejs#37]
I follow the #12 that the example you posted in the end, and I try it in my demo but browser show me this: 
       Uncaught Error: Uncaught TypeError: undefined is not callable

**Comment by luziang0603** [comment]
function a(){
    var key = sb();
}
a();
function sb(){
var vm = new (sablejs ())();
const vConsole = vm.createObject();
const vLog = vm.createFunction("log", function () {
  const temp = [];
  for (let i = 0; i < arguments.length; i++) {
    temp.push(vm.asString(arguments[i]));
  }
  console.log(...temp);
  return vm.createUndefined();
});

const vglobal = vm.getGlobal();
const vSign = vm.getProperty(vglobal, "sign");

const vResult = vm.call(vSign, vglobal, vm.createString("Hello World!"));
const result = vm.asString(vResult);
console.log(result); // Hello World, do what you want.

vm.setProperty(vConsole, "log", vLog);
vm.setProperty(vglobal, "console", vConsole);
(async () => {
  var key =vm.run("JTI1N0IlMjUyMm5hbWUlMjUyMiUyNTNBJTI1MjIlMjUyMiUyNTJDJTI1MjJzY3JpcHQlMjUyMiUyNTNBdHJ1ZSUyNTJDJTI1MjJzdHJpY3QlMjUyMiUyNTNBZmFsc2UlMjUyQyUyNTIybGlnaHR3ZWlnaHQlMjUyMiUyNTNBZmFsc2UlMjUyQyUyNTIyYXJndW1lbnRzJTI1MjIlMjUzQWZhbHNlJTI1MkMlMjUyMm51bXBhcmFtcyUyNTIyJTI1M0EwJTI1MkMlMjUyMnBzJTI1MjIlMjUzQSUyNTVCJTI1NUQlMjUyQyUyNTIydnQlMjUyMiUyNTNBJTI1NUIlMjUyMnNpZ24lMjUyMiUyNTVEJTI1MkMlMjUyMmZ0JTI1MjIlMjUzQSUyNTVCJTI1N0IlMjUyMm5hbWUlMjUyMiUyNTNBJTI1MjJzaWduJTI1MjIlMjUyQyUyNTIyc2NyaXB0JTI1MjIlMjUzQWZhbHNlJTI1MkMlMjUyMnN0cmljdCUyNTIyJTI1M0FmYWxzZSUyNTJDJTI1MjJsaWdodHdlaWdodCUyNTIyJTI1M0F0cnVlJTI1MkMlMjUyMmFyZ3VtZW50cyUyNTIyJTI1M0FmYWxzZSUyNTJDJTI1MjJudW1wYXJhbXMlMjUyMiUyNTNBMSUyNTJDJTI1MjJwcyUyNTIyJTI1M0ElMjU1QiUyNTIyZGF0YSUyNTIyJTI1NUQlMjUyQyUyNTIydnQlMjUyMiUyNTNBJTI1NUIlMjUyMmRhdGElMjUyMiUyNTJDJTI1MjJzaWduJTI1MjIlMjU1RCUyNTJDJTI1MjJmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMnN0JTI1MjIlMjUzQSUyNTVCJTI1MjIlMjUyQyUyNTIwZG8lMjUyMHdoYXQlMjUyMHlvdSUyNTIwd2FudCUyNTIyJTI1NUQlMjUyQyUyNTIybnQlMjUyMiUyNTNBJTI1NUIlMjU1RCUyNTJDJTI1MjJldCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMmRmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMm9wY29kZSUyNTIyJTI1M0ElMjU1QjE5JTI1MkMyMiUyNTJDMiUyNTJDMCUyNTJDMjAlMjUyQzElMjUyQzglMjUyQzAlMjUyQzk0JTI1MkM4NiUyNTJDMTQlMjUyQzg2JTI1NUQlMjU3RCUyNTVEJTI1MkMlMjUyMnN0JTI1MjIlMjUzQSUyNTVCJTI1NUQlMjUyQyUyNTIybnQlMjUyMiUyNTNBJTI1NUIlMjU1RCUyNTJDJTI1MjJldCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMmRmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMm9wY29kZSUyNTIyJTI1M0ElMjU1QjklMjUyQzAlMjUyQzIyJTI1MkMxJTI1MkMwJTI1MkMxNCUyNTJDODYlMjU1RCUyNTdE");
  vm.destroy();
})();
return key;
}

**Comment by luziang0603** [comment]
Please forgive my ignorance, I'm noob in js

**Comment by jimzou** [comment]
**vm.run() before vm.call()
but return is not expected results.**

`<html>
<body>
<script src="./runtime.js"></script>
<script>
    var vm = new (sablejs())();

	function a(){
		var key = sb();
	}
	a();

	function sb(){
		const vglobal = vm.getGlobal();
		const vConsole = vm.createObject();
		const vLog = vm.createFunction("log", function () {
			const temp = [];
			for (let i = 0; i < arguments.length; i++) {
				temp.push(vm.asString(arguments[i]));
			}
			console.log(...temp);
			return vm.createUndefined();
		});


		vm.setProperty(vConsole, "log", vLog);
		vm.setProperty(vglobal, "console", vConsole);
		(async () => {
			var key =vm.run("JTI1N0IlMjUyMm5hbWUlMjUyMiUyNTNBJTI1MjIlMjUyMiUyNTJDJTI1MjJzY3JpcHQlMjUyMiUyNTNBdHJ1ZSUyNTJDJTI1MjJzdHJpY3QlMjUyMiUyNTNBZmFsc2UlMjUyQyUyNTIybGlnaHR3ZWlnaHQlMjUyMiUyNTNBZmFsc2UlMjUyQyUyNTIyYXJndW1lbnRzJTI1MjIlMjUzQWZhbHNlJTI1MkMlMjUyMm51bXBhcmFtcyUyNTIyJTI1M0EwJTI1MkMlMjUyMnBzJTI1MjIlMjUzQSUyNTVCJTI1NUQlMjUyQyUyNTIydnQlMjUyMiUyNTNBJTI1NUIlMjUyMmZpYiUyNTIyJTI1MkMlMjUyMnN0YXJ0JTI1MjIlMjUyQyUyNTIyc2lnbiUyNTIyJTI1NUQlMjUyQyUyNTIyZnQlMjUyMiUyNTNBJTI1NUIlMjU3QiUyNTIybmFtZSUyNTIyJTI1M0ElMjUyMmZpYiUyNTIyJTI1MkMlMjUyMnNjcmlwdCUyNTIyJTI1M0FmYWxzZSUyNTJDJTI1MjJzdHJpY3QlMjUyMiUyNTNBZmFsc2UlMjUyQyUyNTIybGlnaHR3ZWlnaHQlMjUyMiUyNTNBdHJ1ZSUyNTJDJTI1MjJhcmd1bWVudHMlMjUyMiUyNTNBZmFsc2UlMjUyQyUyNTIybnVtcGFyYW1zJTI1MjIlMjUzQTElMjUyQyUyNTIycHMlMjUyMiUyNTNBJTI1NUIlMjUyMm4lMjUyMiUyNTVEJTI1MkMlMjUyMnZ0JTI1MjIlMjUzQSUyNTVCJTI1MjJuJTI1MjIlMjUyQyUyNTIyZmliJTI1MjIlMjU1RCUyNTJDJTI1MjJmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMnN0JTI1MjIlMjUzQSUyNTVCJTI1NUQlMjUyQyUyNTIybnQlMjUyMiUyNTNBJTI1NUIyJTI1MkMxJTI1NUQlMjUyQyUyNTIyZXQlMjUyMiUyNTNBJTI1NUIlMjU1RCUyNTJDJTI1MjJkZnQlMjUyMiUyNTNBJTI1NUIlMjU1RCUyNTJDJTI1MjJvcGNvZGUlMjUyMiUyNTNBJTI1NUIxOSUyNTJDMjIlMjUyQzIlMjUyQzAlMjUyQzg2JTI1MkMxJTI1MkMxNiUyNTJDODYlMjUyQzIlMjUyQzIlMjUyQzIwJTI1MkMxJTI1MkM3JTI1MkMwJTI1MkMxMDYlMjUyQzg0JTI1MkM0MCUyNTJDMjAlMjUyQzIlMjUyQzE0JTI1MkMyMCUyNTJDMSUyNTJDNyUyNTJDMSUyNTJDOTglMjUyQzQzJTI1MkMxJTI1MkMyMCUyNTJDMiUyNTJDMTQlMjUyQzIwJTI1MkMxJTI1MkM3JTI1MkMwJTI1MkM5OCUyNTJDNDMlMjUyQzElMjUyQzU3JTI1MkM4MyUyNTJDNDIlMjUyQzIwJTI1MkMxJTI1MkM4NyUyNTJDMTQlMjUyQzg3JTI1NUQlMjU3RCUyNTJDJTI1N0IlMjUyMm5hbWUlMjUyMiUyNTNBJTI1MjJzaWduJTI1MjIlMjUyQyUyNTIyc2NyaXB0JTI1MjIlMjUzQWZhbHNlJTI1MkMlMjUyMnN0cmljdCUyNTIyJTI1M0FmYWxzZSUyNTJDJTI1MjJsaWdodHdlaWdodCUyNTIyJTI1M0F0cnVlJTI1MkMlMjUyMmFyZ3VtZW50cyUyNTIyJTI1M0FmYWxzZSUyNTJDJTI1MjJudW1wYXJhbXMlMjUyMiUyNTNBMSUyNTJDJTI1MjJwcyUyNTIyJTI1M0ElMjU1QiUyNTIyZGF0YSUyNTIyJTI1NUQlMjUyQyUyNTIydnQlMjUyMiUyNTNBJTI1NUIlMjUyMmRhdGElMjUyMiUyNTJDJTI1MjJzaWduJTI1MjIlMjU1RCUyNTJDJTI1MjJmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMnN0JTI1MjIlMjUzQSUyNTVCJTI1MjIlMjUyQyUyNTIwZG8lMjUyMHdoYXQlMjUyMHlvdSUyNTIwd2FudCUyNTIyJTI1NUQlMjUyQyUyNTIybnQlMjUyMiUyNTNBJTI1NUIlMjU1RCUyNTJDJTI1MjJldCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMmRmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMm9wY29kZSUyNTIyJTI1M0ElMjU1QjE5JTI1MkMyMiUyNTJDMiUyNTJDMCUyNTJDODYlMjUyQzklMjUyQzIwJTI1MkM4NiUyNTJDMTAlMjUyQzMlMjUyQzIwJTI1MkMxJTI1MkM4JTI1MkMwJTI1MkM5NSUyNTJDODclMjUyQzE0JTI1MkM4NyUyNTVEJTI1N0QlMjU1RCUyNTJDJTI1MjJzdCUyNTIyJTI1M0ElMjU1QiUyNTIyRGF0ZSUyNTIyJTI1MkMlMjUyMm5vdyUyNTIyJTI1MkMlMjUyMmNvbnNvbGUlMjUyMiUyNTJDJTI1MjJsb2clMjUyMiUyNTJDJTI1MjIlMjU1QklORk8lMjU1RCUyNTIwZmliJTI1M0ElMjUyMCUyNTIyJTI1MkMlMjUyMiUyNTVCSU5GTyUyNTVEJTI1MjB0aW1lJTI1MjBjb25zdW1pbmclMjUzQSUyNTIwJTI1MjIlMjUyQyUyNTIybXMlMjUyMiUyNTVEJTI1MkMlMjUyMm50JTI1MjIlMjUzQSUyNTVCMzAlMjU1RCUyNTJDJTI1MjJldCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMmRmdCUyNTIyJTI1M0ElMjU1QiUyNTVEJTI1MkMlMjUyMm9wY29kZSUyNTIyJTI1M0ElMjU1QjklMjUyQzAlMjUyQzIyJTI1MkMxJTI1MkMwJTI1MkM5JTI1MkMxJTI1MkMyMiUyNTJDMyUyNTJDMCUyNTJDMTQlMjUyQzg2JTI1MkMxJTI1MkMwJTI1MkM4NiUyNTJDNSUyNTJDMCUyNTJDMjclMjUyQzAlMjUyQzElMjUyQzM1JTI1MkMxJTI1MkMzJTI1MkM0MyUyNTJDMCUyNTJDMjIlMjUyQzIlMjUyQzAlMjUyQzg2JTI1MkM2JTI1MkMwJTI1MkMwJTI1MkMyNyUyNTJDMiUyNTJDMSUyNTJDMzUlMjUyQzMlMjUyQzMlMjUyQzglMjUyQzQlMjUyQzIwJTI1MkMxJTI1MkMxNCUyNTJDNyUyNTJDMCUyNTJDNDMlMjUyQzElMjUyQzk3JTI1MkM0MyUyNTJDMSUyNTJDODYlMjUyQzclMjUyQzAlMjUyQzAlMjUyQzI3JTI1MkMyJTI1MkMxJTI1MkMzNSUyNTJDMyUyNTJDMyUyNTJDOCUyNTJDNSUyNTJDMjclMjUyQzAlMjUyQzElMjUyQzM1JTI1MkMxJTI1MkMzJTI1MkM0MyUyNTJDMCUyNTJDMjAlMjUyQzIlMjUyQzU4JTI1MkM5NyUyNTJDOCUyNTJDNiUyNTJDOTUlMjUyQzQzJTI1MkMxJTI1MkM4NiUyNTJDOSUyNTJDMCUyNTJDODclMjU1RCUyNTdE");

			const vSign = vm.getProperty(vglobal, "sign");

			const vResult = vm.call(vSign,  vm.createString("Hello World!"));
			const result = vm.asString(vResult);
			console.log(result); // Hello World, do what you want.

			vm.destroy();
		})();
	}
</script>
</body>
</html>`

**Comment by ErosZy** [comment]
please follow this issue: https://github.com/sablejs/sablejs/issues/38
