### ISSUE TITLE
is sablejs2.0 still wip or not maintained any more?

### ISSUE THREAD

**Issue by AndyBoat** [ErosZy/sablejs#39]
Inspired by [this article](https://gmtc.infoq.cn/2021/shenzhen/presentation/3927),  but it looks  like this repo has been inactive for a while, so I am  curious about the progress and feature of sablejs.

**Comment by ErosZy** [comment]
@AndyBoat I'm working at [quickjs](https://github.com/openwebf/quickjs) now, the time for sablejs is relatively low 😨

**Comment by AndyBoat** [comment]
Thank you! And would you mind giveing some alternatives to `sablejs` ?

**Comment by ErosZy** [comment]
@AndyBoat https://www.npmjs.com/package/quickjs-emscripten is just ok, you also can check [sval](https://github.com/Siubaak/sval).

**Comment by AndyBoat** [comment]
Thanks!
